language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: aeLXRC5oFSddwnZt1/7G2/OHr7jDbxz0ET7sej3I+eSbe3N5vbzQ6FC08es4l89l54ciXd90I1g2BMw7DTYKOO373FP78XPdAEbifJTU4DGd6fCELmoTtUPhjunBIk7E49hisPbv82892IYYA7qi/hzG548cPyZ1IgiJjq0NCsc=
