sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - rabbitmq
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- ./mvnw install -P docs -q -U -DskipTests=true $MVN_LOCAL_OPTS
- '[ "${MVN_GOAL}" == "deploy" ] && ./docs/src/main/asciidoc/ghpages.sh || echo "Not updating docs"'
script:
- './mvnw -s .settings.xml $MVN_GOAL $MVN_PROFILE -nsu $MVN_LOCAL_OPTS'
env:
  global:
  - MVN_LOCAL_OPTS=-Dmaven.source.skip=true -Dmaven.javadoc.skip=true -Dmaven.test.redirectTestOutputToFile=true
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep -q "^.*/.*$" && echo true || echo false)
  - SPRING_CLOUD_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^spring-cloud/.*$" && echo true || echo false)
  - MVN_GOAL=install
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - MILESTONE=$(echo ${VERSION} | egrep 'M|RC' && echo true || echo false)
  - MVN_PROFILE=$([ "${MILESTONE}" == "true" ] && echo -P milestone)
  - JAVA_OPTS="-Xmx1024m -XX:CICompilerCount=1 -XX:TieredStopAtLevel=1 -Djava.security.egd=file:/dev/./urandom"
  - secure: aeLXRC5oFSddwnZt1/7G2/OHr7jDbxz0ET7sej3I+eSbe3N5vbzQ6FC08es4l89l54ciXd90I1g2BMw7DTYKOO373FP78XPdAEbifJTU4DGd6fCELmoTtUPhjunBIk7E49hisPbv82892IYYA7qi/hzG548cPyZ1IgiJjq0NCsc=
